[project]
name = "edudata"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.edu-mngt]
path = "contracts/edu-mngt.clar"
depends_on = []
